// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/db.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1871523213;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib_stoolap_flutter',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiDbStoolapDbBatchExecute(
      {required StoolapDb that, required List<String> sqls});

  Future<void> crateApiDbStoolapDbBegin({required StoolapDb that});

  Future<StoolapDb> crateApiDbStoolapDbCloneHandle({required StoolapDb that});

  Future<void> crateApiDbStoolapDbCommit({required StoolapDb that});

  Future<void> crateApiDbStoolapDbExecute(
      {required StoolapDb that,
      required String sql,
      required List<StoolapValue> params});

  Future<List<StoolapRow>> crateApiDbStoolapDbExecuteWithResults(
      {required StoolapDb that,
      required String sql,
      required List<StoolapValue> params});

  Future<String> crateApiDbStoolapDbExplain(
      {required StoolapDb that,
      required String sql,
      required List<StoolapValue> params});

  Future<StoolapDb> crateApiDbStoolapDbOpen({required String dsn});

  Future<List<StoolapRow>> crateApiDbStoolapDbPragma(
      {required StoolapDb that, required String name, String? value});

  Future<List<StoolapRow>> crateApiDbStoolapDbQuery(
      {required StoolapDb that,
      required String sql,
      required List<StoolapValue> params});

  Future<void> crateApiDbStoolapDbReleaseSavepoint(
      {required StoolapDb that, required String name});

  Future<void> crateApiDbStoolapDbRollback({required StoolapDb that});

  Future<void> crateApiDbStoolapDbRollbackToSavepoint(
      {required StoolapDb that, required String name});

  Future<void> crateApiDbStoolapDbSavepoint(
      {required StoolapDb that, required String name});

  Future<void> crateApiDbStoolapDbSetupLogStream(
      {required DefaultStreamSinkString sink});

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_DefaultStreamSinkString;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_DefaultStreamSinkString;

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_DefaultStreamSinkStringPtr;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_StoolapDb;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_StoolapDb;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_StoolapDbPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiDbStoolapDbBatchExecute(
      {required StoolapDb that, required List<String> sqls}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStoolapDb(
            that, serializer);
        sse_encode_list_String(sqls, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDbStoolapDbBatchExecuteConstMeta,
      argValues: [that, sqls],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDbStoolapDbBatchExecuteConstMeta =>
      const TaskConstMeta(
        debugName: "StoolapDb_batch_execute",
        argNames: ["that", "sqls"],
      );

  @override
  Future<void> crateApiDbStoolapDbBegin({required StoolapDb that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStoolapDb(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDbStoolapDbBeginConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDbStoolapDbBeginConstMeta => const TaskConstMeta(
        debugName: "StoolapDb_begin",
        argNames: ["that"],
      );

  @override
  Future<StoolapDb> crateApiDbStoolapDbCloneHandle({required StoolapDb that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStoolapDb(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStoolapDb,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDbStoolapDbCloneHandleConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDbStoolapDbCloneHandleConstMeta =>
      const TaskConstMeta(
        debugName: "StoolapDb_clone_handle",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiDbStoolapDbCommit({required StoolapDb that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStoolapDb(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDbStoolapDbCommitConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDbStoolapDbCommitConstMeta => const TaskConstMeta(
        debugName: "StoolapDb_commit",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiDbStoolapDbExecute(
      {required StoolapDb that,
      required String sql,
      required List<StoolapValue> params}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStoolapDb(
            that, serializer);
        sse_encode_String(sql, serializer);
        sse_encode_list_stoolap_value(params, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDbStoolapDbExecuteConstMeta,
      argValues: [that, sql, params],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDbStoolapDbExecuteConstMeta => const TaskConstMeta(
        debugName: "StoolapDb_execute",
        argNames: ["that", "sql", "params"],
      );

  @override
  Future<List<StoolapRow>> crateApiDbStoolapDbExecuteWithResults(
      {required StoolapDb that,
      required String sql,
      required List<StoolapValue> params}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStoolapDb(
            that, serializer);
        sse_encode_String(sql, serializer);
        sse_encode_list_stoolap_value(params, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_stoolap_row,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDbStoolapDbExecuteWithResultsConstMeta,
      argValues: [that, sql, params],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDbStoolapDbExecuteWithResultsConstMeta =>
      const TaskConstMeta(
        debugName: "StoolapDb_execute_with_results",
        argNames: ["that", "sql", "params"],
      );

  @override
  Future<String> crateApiDbStoolapDbExplain(
      {required StoolapDb that,
      required String sql,
      required List<StoolapValue> params}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStoolapDb(
            that, serializer);
        sse_encode_String(sql, serializer);
        sse_encode_list_stoolap_value(params, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDbStoolapDbExplainConstMeta,
      argValues: [that, sql, params],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDbStoolapDbExplainConstMeta => const TaskConstMeta(
        debugName: "StoolapDb_explain",
        argNames: ["that", "sql", "params"],
      );

  @override
  Future<StoolapDb> crateApiDbStoolapDbOpen({required String dsn}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dsn, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStoolapDb,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDbStoolapDbOpenConstMeta,
      argValues: [dsn],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDbStoolapDbOpenConstMeta => const TaskConstMeta(
        debugName: "StoolapDb_open",
        argNames: ["dsn"],
      );

  @override
  Future<List<StoolapRow>> crateApiDbStoolapDbPragma(
      {required StoolapDb that, required String name, String? value}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStoolapDb(
            that, serializer);
        sse_encode_String(name, serializer);
        sse_encode_opt_String(value, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_stoolap_row,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDbStoolapDbPragmaConstMeta,
      argValues: [that, name, value],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDbStoolapDbPragmaConstMeta => const TaskConstMeta(
        debugName: "StoolapDb_pragma",
        argNames: ["that", "name", "value"],
      );

  @override
  Future<List<StoolapRow>> crateApiDbStoolapDbQuery(
      {required StoolapDb that,
      required String sql,
      required List<StoolapValue> params}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStoolapDb(
            that, serializer);
        sse_encode_String(sql, serializer);
        sse_encode_list_stoolap_value(params, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_stoolap_row,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDbStoolapDbQueryConstMeta,
      argValues: [that, sql, params],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDbStoolapDbQueryConstMeta => const TaskConstMeta(
        debugName: "StoolapDb_query",
        argNames: ["that", "sql", "params"],
      );

  @override
  Future<void> crateApiDbStoolapDbReleaseSavepoint(
      {required StoolapDb that, required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStoolapDb(
            that, serializer);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDbStoolapDbReleaseSavepointConstMeta,
      argValues: [that, name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDbStoolapDbReleaseSavepointConstMeta =>
      const TaskConstMeta(
        debugName: "StoolapDb_release_savepoint",
        argNames: ["that", "name"],
      );

  @override
  Future<void> crateApiDbStoolapDbRollback({required StoolapDb that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStoolapDb(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDbStoolapDbRollbackConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDbStoolapDbRollbackConstMeta =>
      const TaskConstMeta(
        debugName: "StoolapDb_rollback",
        argNames: ["that"],
      );

  @override
  Future<void> crateApiDbStoolapDbRollbackToSavepoint(
      {required StoolapDb that, required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStoolapDb(
            that, serializer);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDbStoolapDbRollbackToSavepointConstMeta,
      argValues: [that, name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDbStoolapDbRollbackToSavepointConstMeta =>
      const TaskConstMeta(
        debugName: "StoolapDb_rollback_to_savepoint",
        argNames: ["that", "name"],
      );

  @override
  Future<void> crateApiDbStoolapDbSavepoint(
      {required StoolapDb that, required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStoolapDb(
            that, serializer);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDbStoolapDbSavepointConstMeta,
      argValues: [that, name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDbStoolapDbSavepointConstMeta =>
      const TaskConstMeta(
        debugName: "StoolapDb_savepoint",
        argNames: ["that", "name"],
      );

  @override
  Future<void> crateApiDbStoolapDbSetupLogStream(
      {required DefaultStreamSinkString sink}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDefaultStreamSinkString(
            sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDbStoolapDbSetupLogStreamConstMeta,
      argValues: [sink],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiDbStoolapDbSetupLogStreamConstMeta =>
      const TaskConstMeta(
        debugName: "StoolapDb_setup_log_stream",
        argNames: ["sink"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleGreetConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta => const TaskConstMeta(
        debugName: "greet",
        argNames: ["name"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_DefaultStreamSinkString => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDefaultStreamSinkString;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_DefaultStreamSinkString => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDefaultStreamSinkString;

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_StoolapDb => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStoolapDb;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_StoolapDb => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStoolapDb;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  DefaultStreamSinkString
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDefaultStreamSinkString(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DefaultStreamSinkStringImpl.frbInternalDcoDecode(
        raw as List<dynamic>);
  }

  @protected
  StoolapDb
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStoolapDb(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return StoolapDbImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  StoolapDb
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStoolapDb(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return StoolapDbImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  DefaultStreamSinkString
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDefaultStreamSinkString(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DefaultStreamSinkStringImpl.frbInternalDcoDecode(
        raw as List<dynamic>);
  }

  @protected
  StoolapDb
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStoolapDb(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return StoolapDbImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float32List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<StoolapRow> dco_decode_list_stoolap_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_stoolap_row).toList();
  }

  @protected
  List<StoolapValue> dco_decode_list_stoolap_value(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_stoolap_value).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  StoolapRow dco_decode_stoolap_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return StoolapRow(
      columns: dco_decode_list_String(arr[0]),
      values: dco_decode_list_stoolap_value(arr[1]),
    );
  }

  @protected
  StoolapValue dco_decode_stoolap_value(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return StoolapValue_Integer(
          dco_decode_i_64(raw[1]),
        );
      case 1:
        return StoolapValue_Float(
          dco_decode_f_64(raw[1]),
        );
      case 2:
        return StoolapValue_Text(
          dco_decode_String(raw[1]),
        );
      case 3:
        return StoolapValue_Boolean(
          dco_decode_bool(raw[1]),
        );
      case 4:
        return StoolapValue_Vector(
          dco_decode_list_prim_f_32_strict(raw[1]),
        );
      case 5:
        return StoolapValue_Json(
          dco_decode_String(raw[1]),
        );
      case 6:
        return StoolapValue_Timestamp(
          dco_decode_i_64(raw[1]),
        );
      case 7:
        return StoolapValue_Date(
          dco_decode_i_64(raw[1]),
        );
      case 8:
        return StoolapValue_Null();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  DefaultStreamSinkString
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDefaultStreamSinkString(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return DefaultStreamSinkStringImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  StoolapDb
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStoolapDb(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return StoolapDbImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  StoolapDb
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStoolapDb(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return StoolapDbImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  DefaultStreamSinkString
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDefaultStreamSinkString(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return DefaultStreamSinkStringImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  StoolapDb
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStoolapDb(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return StoolapDbImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat32List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<StoolapRow> sse_decode_list_stoolap_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <StoolapRow>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_stoolap_row(deserializer));
    }
    return ans_;
  }

  @protected
  List<StoolapValue> sse_decode_list_stoolap_value(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <StoolapValue>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_stoolap_value(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  StoolapRow sse_decode_stoolap_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_columns = sse_decode_list_String(deserializer);
    var var_values = sse_decode_list_stoolap_value(deserializer);
    return StoolapRow(columns: var_columns, values: var_values);
  }

  @protected
  StoolapValue sse_decode_stoolap_value(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_i_64(deserializer);
        return StoolapValue_Integer(var_field0);
      case 1:
        var var_field0 = sse_decode_f_64(deserializer);
        return StoolapValue_Float(var_field0);
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return StoolapValue_Text(var_field0);
      case 3:
        var var_field0 = sse_decode_bool(deserializer);
        return StoolapValue_Boolean(var_field0);
      case 4:
        var var_field0 = sse_decode_list_prim_f_32_strict(deserializer);
        return StoolapValue_Vector(var_field0);
      case 5:
        var var_field0 = sse_decode_String(deserializer);
        return StoolapValue_Json(var_field0);
      case 6:
        var var_field0 = sse_decode_i_64(deserializer);
        return StoolapValue_Timestamp(var_field0);
      case 7:
        var var_field0 = sse_decode_i_64(deserializer);
        return StoolapValue_Date(var_field0);
      case 8:
        return StoolapValue_Null();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDefaultStreamSinkString(
          DefaultStreamSinkString self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as DefaultStreamSinkStringImpl).frbInternalSseEncode(move: true),
        serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStoolapDb(
          StoolapDb self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as StoolapDbImpl).frbInternalSseEncode(move: true), serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStoolapDb(
          StoolapDb self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as StoolapDbImpl).frbInternalSseEncode(move: false), serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerDefaultStreamSinkString(
          DefaultStreamSinkString self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as DefaultStreamSinkStringImpl).frbInternalSseEncode(move: null),
        serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerStoolapDb(
          StoolapDb self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as StoolapDbImpl).frbInternalSseEncode(move: null), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_32_strict(
      Float32List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_stoolap_row(
      List<StoolapRow> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_stoolap_row(item, serializer);
    }
  }

  @protected
  void sse_encode_list_stoolap_value(
      List<StoolapValue> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_stoolap_value(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_stoolap_row(StoolapRow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.columns, serializer);
    sse_encode_list_stoolap_value(self.values, serializer);
  }

  @protected
  void sse_encode_stoolap_value(StoolapValue self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case StoolapValue_Integer(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_i_64(field0, serializer);
      case StoolapValue_Float(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_f_64(field0, serializer);
      case StoolapValue_Text(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
      case StoolapValue_Boolean(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_bool(field0, serializer);
      case StoolapValue_Vector(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_list_prim_f_32_strict(field0, serializer);
      case StoolapValue_Json(field0: final field0):
        sse_encode_i_32(5, serializer);
        sse_encode_String(field0, serializer);
      case StoolapValue_Timestamp(field0: final field0):
        sse_encode_i_32(6, serializer);
        sse_encode_i_64(field0, serializer);
      case StoolapValue_Date(field0: final field0):
        sse_encode_i_32(7, serializer);
        sse_encode_i_64(field0, serializer);
      case StoolapValue_Null():
        sse_encode_i_32(8, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class DefaultStreamSinkStringImpl extends RustOpaque
    implements DefaultStreamSinkString {
  // Not to be used by end users
  DefaultStreamSinkStringImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  DefaultStreamSinkStringImpl.frbInternalSseDecode(
      BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance.api.rust_arc_increment_strong_count_DefaultStreamSinkString,
    rustArcDecrementStrongCount: RustLib
        .instance.api.rust_arc_decrement_strong_count_DefaultStreamSinkString,
    rustArcDecrementStrongCountPtr: RustLib.instance.api
        .rust_arc_decrement_strong_count_DefaultStreamSinkStringPtr,
  );
}

@sealed
class StoolapDbImpl extends RustOpaque implements StoolapDb {
  // Not to be used by end users
  StoolapDbImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  StoolapDbImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_StoolapDb,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_StoolapDb,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_StoolapDbPtr,
  );

  /// Executes a batch of SQL statements efficiently.
  Future<void> batchExecute({required List<String> sqls}) =>
      RustLib.instance.api
          .crateApiDbStoolapDbBatchExecute(that: this, sqls: sqls);

  /// Explicitly begins a transaction.
  Future<void> begin() => RustLib.instance.api.crateApiDbStoolapDbBegin(
        that: this,
      );

  /// Clones the database handle, creating a new connection with independent transaction state.
  Future<StoolapDb> cloneHandle() =>
      RustLib.instance.api.crateApiDbStoolapDbCloneHandle(
        that: this,
      );

  /// Commits the active transaction.
  Future<void> commit() => RustLib.instance.api.crateApiDbStoolapDbCommit(
        that: this,
      );

  /// Executes a SQL statement with parameters.
  Future<void> execute(
          {required String sql, required List<StoolapValue> params}) =>
      RustLib.instance.api
          .crateApiDbStoolapDbExecute(that: this, sql: sql, params: params);

  /// Executes a statement and returns results (e.g., for RETURNING clause).
  Future<List<StoolapRow>> executeWithResults(
          {required String sql, required List<StoolapValue> params}) =>
      RustLib.instance.api.crateApiDbStoolapDbExecuteWithResults(
          that: this, sql: sql, params: params);

  /// Returns the execution plan and profiling info for a SQL statement.
  Future<String> explain(
          {required String sql, required List<StoolapValue> params}) =>
      RustLib.instance.api
          .crateApiDbStoolapDbExplain(that: this, sql: sql, params: params);

  /// Executes a PRAGMA command to configure or inspect the database engine.
  Future<List<StoolapRow>> pragma({required String name, String? value}) =>
      RustLib.instance.api
          .crateApiDbStoolapDbPragma(that: this, name: name, value: value);

  /// Queries the database and returns a list of rows.
  Future<List<StoolapRow>> query(
          {required String sql, required List<StoolapValue> params}) =>
      RustLib.instance.api
          .crateApiDbStoolapDbQuery(that: this, sql: sql, params: params);

  /// Releases a named savepoint.
  Future<void> releaseSavepoint({required String name}) => RustLib.instance.api
      .crateApiDbStoolapDbReleaseSavepoint(that: this, name: name);

  /// Rolls back the active transaction.
  Future<void> rollback() => RustLib.instance.api.crateApiDbStoolapDbRollback(
        that: this,
      );

  /// Rolls back to a named savepoint.
  Future<void> rollbackToSavepoint({required String name}) =>
      RustLib.instance.api
          .crateApiDbStoolapDbRollbackToSavepoint(that: this, name: name);

  /// Creates a named savepoint.
  Future<void> savepoint({required String name}) =>
      RustLib.instance.api.crateApiDbStoolapDbSavepoint(that: this, name: name);
}
