// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'db.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<StoolapDb>>
abstract class StoolapDb implements RustOpaqueInterface {
  static Future<void> begin() =>
      RustLib.instance.api.crateApiDbStoolapDbBegin();

  static Future<void> close() =>
      RustLib.instance.api.crateApiDbStoolapDbClose();

  static Future<void> commit() =>
      RustLib.instance.api.crateApiDbStoolapDbCommit();

  static Future<void> execute({
    required String sql,
    required List<String> params,
  }) =>
      RustLib.instance.api.crateApiDbStoolapDbExecute(sql: sql, params: params);

  static Future<void> open({required String path}) =>
      RustLib.instance.api.crateApiDbStoolapDbOpen(path: path);

  static Future<List<StoolapRow>> query({
    required String sql,
    required List<String> params,
  }) => RustLib.instance.api.crateApiDbStoolapDbQuery(sql: sql, params: params);

  static Future<void> rollback() =>
      RustLib.instance.api.crateApiDbStoolapDbRollback();
}

class StoolapRow {
  final List<String> columns;
  final List<StoolapValue> values;

  const StoolapRow({required this.columns, required this.values});

  @override
  int get hashCode => columns.hashCode ^ values.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoolapRow &&
          runtimeType == other.runtimeType &&
          columns == other.columns &&
          values == other.values;
}

@freezed
sealed class StoolapValue with _$StoolapValue {
  const StoolapValue._();

  const factory StoolapValue.integer(PlatformInt64 field0) =
      StoolapValue_Integer;
  const factory StoolapValue.float(double field0) = StoolapValue_Float;
  const factory StoolapValue.text(String field0) = StoolapValue_Text;
  const factory StoolapValue.vector(Float32List field0) = StoolapValue_Vector;
  const factory StoolapValue.null_() = StoolapValue_Null;
}
