// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'db.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `convert_params`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DefaultStreamSink < String >>>
abstract class DefaultStreamSinkString implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<StoolapDb>>
abstract class StoolapDb implements RustOpaqueInterface {
  Future<void> batchExecute({required List<String> sqls});

  Future<void> begin();

  Future<StoolapDb> cloneHandle();

  Future<void> commit();

  Future<void> execute(
      {required String sql, required List<StoolapValue> params});

  Future<List<StoolapRow>> executeWithResults(
      {required String sql, required List<StoolapValue> params});

  Future<String> explain(
      {required String sql, required List<StoolapValue> params});

  static Future<StoolapDb> open({required String dsn}) =>
      RustLib.instance.api.crateApiDbStoolapDbOpen(dsn: dsn);

  Future<List<StoolapRow>> pragma({required String name, String? value});

  Future<List<StoolapRow>> query(
      {required String sql, required List<StoolapValue> params});

  Future<void> releaseSavepoint({required String name});

  Future<void> rollback();

  Future<void> rollbackToSavepoint({required String name});

  Future<void> savepoint({required String name});

  static Future<void> setupLogStream({required DefaultStreamSinkString sink}) =>
      RustLib.instance.api.crateApiDbStoolapDbSetupLogStream(sink: sink);
}

class StoolapRow {
  final List<String> columns;
  final List<StoolapValue> values;

  const StoolapRow({
    required this.columns,
    required this.values,
  });

  @override
  int get hashCode => columns.hashCode ^ values.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StoolapRow &&
          runtimeType == other.runtimeType &&
          columns == other.columns &&
          values == other.values;
}

@freezed
sealed class StoolapValue with _$StoolapValue {
  const StoolapValue._();

  const factory StoolapValue.integer(
    PlatformInt64 field0,
  ) = StoolapValue_Integer;
  const factory StoolapValue.float(
    double field0,
  ) = StoolapValue_Float;
  const factory StoolapValue.text(
    String field0,
  ) = StoolapValue_Text;
  const factory StoolapValue.boolean(
    bool field0,
  ) = StoolapValue_Boolean;
  const factory StoolapValue.vector(
    Float32List field0,
  ) = StoolapValue_Vector;
  const factory StoolapValue.json(
    String field0,
  ) = StoolapValue_Json;
  const factory StoolapValue.timestamp(
    PlatformInt64 field0,
  ) = StoolapValue_Timestamp;
  const factory StoolapValue.date(
    PlatformInt64 field0,
  ) = StoolapValue_Date;
  const factory StoolapValue.null_() = StoolapValue_Null;
}
